export type Locale = 'en' | 'pt';

export const content = {
  en: {
    banner: "🔥 Free Fast Shipping across Portugal & Europe on all orders this week!",
    nav: {
      features: "Why TapFive",
      howItWorks: "How It Works",
      videoReviews: "Customer Stories",
      calculator: "Simulator",
      pricing: "Product",
      faq: "FAQ",
      buyNow: "Order Card",
    },
    hero: {
      badge: "Rated 4.9/5 by 250+ Local Businesses",
      titleStart: "Get 3x More Google Reviews in",
      titleHighlight: "Seconds with 1 Tap.",
      description: "No more awkward asking or paper cards that get thrown away. Customers simply tap their phone on your counter card to open your 5-star Google review box instantly.",
      ctaPrimary: "Order Review Card — €19.99",
      ctaSecondary: "How It Works",
      bullet1: "Works with all iPhone & Android",
      bullet2: "Zero monthly fees or subscriptions",
      bullet3: "Dispatched in 24–48 hours",
      statsTitle: "Average business impact:",
      stats1Value: "+240%",
      stats1Label: "Monthly Reviews",
      stats2Value: "4.8★",
      stats2Label: "Average Google Score",
      stats3Value: "3 sec",
      stats3Label: "To Submit Review",
    },
    cardPreview: {
      title: "TapFive Review Card",
      subtitle: "Contactless NFC Chip",
      tapInstruction: "Tap back of phone against card",
      readyBadge: "Passive NFC Chip • Never Needs Battery",
    },
    howItWorks: {
      tag: "Zero Friction",
      title: "How It Works in 3 Simple Steps",
      subtitle: "Place it by your register, restaurant bill, or reception desk.",
      step1Title: "1. Present the Card",
      step1Desc: "Keep the sleek matte card on your counter or present it right after a great customer experience.",
      step2Title: "2. Customer Taps Phone",
      step2Desc: "Customer touches their iPhone or Android to the card. No app or download needed.",
      step3Title: "3. 5-Star Review Left",
      step3Desc: "Your direct Google Business review box pops up on their screen with 5 stars selected. Done in 3 seconds.",
    },
    calculator: {
      tag: "Revenue & Reviews",
      title: "How Many Reviews Are You Missing Out On?",
      subtitle: "Most happy customers want to leave a review, but 95% forget the second they walk out your door.",
      sliderLabel: "Estimated happy customers per day:",
      resultTitle: "New Reviews Gained:",
      perMonth: "/ month",
      explanation: "With just 1 card at checkout, capturing 1 out of 10 happy customers boosts your local Google Maps ranking to #1 in your area.",
    },
    pricing: {
      tag: "Transparent Pricing",
      title: "One-time Payment. No Subscriptions Ever.",
      subtitle: "No hidden fees. One upfront payment with lifetime card utility.",
      blank: {
        title: "Blank Card",
        tagline: "Configure it yourself in 2 minutes",
        price: "€19.99",
        originalPrice: "€29.99",
        features: [
          "1x Premium Matte NFC Contactless Review Card",
          "Official Google Review layout",
          "Compatible with all modern iPhone & Android devices",
          "Simple self-programming guide included",
          "No app required for your customers",
          "Free standard shipping",
        ],
        cta: "Buy Blank Card (€19.99)",
      },
      preProgrammed: {
        badge: "MOST POPULAR",
        title: "Pre-Programmed Card",
        tagline: "We configure your Google profile before shipping",
        price: "€24.99",
        originalPrice: "€39.99",
        features: [
          "Everything in Blank Card",
          "Pre-encoded with your direct 5-star review link",
          "Ready to use straight out of the box",
          "Tested on iOS and Android before dispatch",
          "Priority 24h dispatch",
          "Lifetime link support",
        ],
        cta: "Buy Pre-Programmed (€24.99)",
        inputLabel: "Google Maps link or Business Name & City:",
        inputPlaceholder: "e.g. Restaurante Solar dos Presuntos, Lisboa",
        inputHelp: "We look up your official profile and encode the chip before shipping.",
        inputError: "Please enter your business link or name so we can configure your card.",
      },
      gbpSetup: {
        badge: "FULL SERVICE SETUP",
        title: "Google Business Setup & SEO",
        tagline: "Complete profile creation, verification & ranking optimization",
        price: "€199.99",
        originalPrice: "€349.99",
        freeCardBadge: "🎁 Includes 1 FREE Pre-Programmed Card",
        features: [
          "Complete Google Business Profile creation or audit",
          "Official Google verification support",
          "Local SEO ranking keywords optimization",
          "Hours, photos, services catalog & attributes setup",
          "1x Pre-Programmed NFC Card included for FREE (€24.99 value)",
          "Direct strategy consultation for continuous reviews",
        ],
        cta: "Order Setup + Free Card (€199.99)",
        inputLabel: "Business Name, City & Phone / WhatsApp:",
        inputPlaceholder: "e.g. Clínica Sorriso, Porto (+351 912 345 678)",
        inputHelp: "Our specialist contacts you within 24 hours to begin.",
        inputError: "Please enter your business name and contact number.",
      },
      guarantee: "30-Day Money-Back Guarantee. If you are not 100% satisfied, we refund your order in full.",
    },
    useCases: {
      tag: "Built For High-Traffic Counters",
      title: "Trusted in Over 250+ Salons, Clinics & Restaurants",
      items: [
        { icon: "Utensils", title: "Restaurants & Cafés", desc: "Bring with the bill to collect reviews while customers are delighted.", image: "/media/card-cafe-restaurant.webp" },
        { icon: "Scissors", title: "Barbershops & Salons", desc: "Show off the fresh style and tap before the customer heads out.", image: "/media/card-salon-barber.webp" },
        { icon: "Stethoscope", title: "Clinics & Dentists", desc: "Place on the reception counter for patients checking out.", image: "/media/card-proof-metrics.webp" },
        { icon: "ShoppingBag", title: "Retail & Studios", desc: "Keep right by the payment terminal as the final checkout step.", image: "/media/card-podium-studio.webp" },
      ],
    },
    videoReel: {
      tag: "Real Customer Results",
      title: "See How Business Owners Get 3x More Reviews",
      subtitle: "Watch real merchants collect effortless 5-star Google ratings right at the checkout counter.",
      video1Caption: "“I spent months chasing down Google reviews...”",
      video1Role: "Salon & Studio Owner",
      video2Caption: "“Texting clients only for them to forget...”",
      video2Role: "Aesthetic Clinic Manager",
      video3Caption: "“Our Google Maps ranking jumped to #1 in our city...”",
      video3Role: "Barbershop Founder",
      video4Caption: "“Customers tap with a smile before leaving...”",
      video4Role: "Boutique Cafe Owner",
      video5Caption: "“Tripled our monthly review volume in 30 days...”",
      video5Role: "Dental Clinic Director",
      video6Caption: "“Zero monthly fees and it just works every time.”",
      video6Role: "Restaurant Manager",
      soundOn: "Tap for sound",
      soundOff: "Mute",
    },
    pdp: {
      category: "SMART NFC HARDWARE",
      title: "TapFive™ NFC Google Review Card",
      rating: "4.9",
      reviewCount: "250+ reviews",
      inStock: "In Stock — Dispatched in 24–48h",
      chooseEdition: "Select Edition:",
      variantBlank: {
        name: "Blank Card",
        desc: "Configure yourself in 2 minutes with free app",
        price: "€19.99",
        originalPrice: "€29.99",
      },
      variantPre: {
        name: "Pre-Programmed",
        badge: "MOST POPULAR",
        desc: "We encode your 5-star link before shipping",
        price: "€24.99",
        originalPrice: "€39.99",
      },
      variantGbp: {
        name: "Full Setup & SEO + Free Card",
        badge: "BEST VALUE",
        desc: "Complete profile optimization & verification",
        price: "€199.99",
        originalPrice: "€349.99",
      },
      buyNow: "Order Now",
      featuresTitle: "What's Included:",
      features: [
        "1x Matte PVC Contactless Card with NTAG215 chip",
        "Instant review prompt on iPhone & Android",
        "Zero monthly fees or subscriptions forever",
        "30-day money-back satisfaction guarantee",
      ],
      inputLabelPre: "Your Google Maps link or Business Name & City:",
      inputPlaceholderPre: "e.g. Restaurante Solar dos Presuntos, Lisboa",
      inputHelpPre: "We encode and test your 5-star direct link prior to shipping.",
      inputLabelGbp: "Business Name, City & Phone / WhatsApp:",
      inputPlaceholderGbp: "e.g. Clínica Sorriso, Porto (+351 912 345 678)",
      inputHelpGbp: "Our setup specialist will reach out within 24 hours.",
    },
    trust: {
      title: "Bank-Grade Security & Peace of Mind",
      ssl: "256-Bit SSL Encryption",
      sslDesc: "Your data and checkout are protected by Stripe's bank-grade security protocols.",
      shipping: "Express Dispatch",
      shippingDesc: "Fast insured shipping. Dispatched directly within 24 to 48 hours.",
      guarantee: "30-Day Guarantee",
      guaranteeDesc: "Not thrilled with your results? We offer a no-questions-asked full refund.",
      noSubs: "Zero Monthly Fees",
      noSubsDesc: "Pay once and use forever. No hidden software fees, charges, or subscriptions.",
    },
    faq: {
      tag: "Got Questions?",
      title: "Frequently Asked Questions",
      items: [
        {
          q: "Does the card require a battery or charging?",
          a: "No. The card uses passive NFC technology powered by induction from the customer's phone during the tap. It will last for years with zero charging.",
        },
        {
          q: "Does the customer need to install an app?",
          a: "Never. iPhone and all modern Android devices read the chip natively. A prompt pops up instantly directing them straight to your review page.",
        },
        {
          q: "Which phones are compatible with the card?",
          a: "Virtually all modern smartphones: all iPhones (iPhone XR and newer) and over 95% of Android devices produced in the last 8+ years.",
        },
        {
          q: "How does the Pre-Programmed option work?",
          a: "Enter your business name or Google Maps link at checkout. We find your official profile, encode your direct review link onto the chip, verify it, and ship it ready to use.",
        },
        {
          q: "Can I change the link on the card later?",
          a: "Yes. You can rewrite the card anytime using any free NFC app (such as 'NFC Tools' on iOS or Android) if your location or name changes.",
        },
        {
          q: "Are there any recurring monthly fees?",
          a: "Zero. You pay once for the card and own it forever. There are never any subscriptions or recurring charges.",
        },
      ],
    },
    footer: {
      rights: "All rights reserved. Not affiliated with Google LLC.",
      secureNotice: "100% Secure Checkout with Stripe 256-Bit SSL Encryption.",
      terms: "Terms of Service",
      privacy: "Privacy Policy",
      refunds: "Refund Policy",
      support: "WhatsApp: +351 928 248 322",
    },
    success: {
      badge: "Payment Confirmed",
      title: "Thank You for Your Order!",
      subtitle: "We're already preparing your TapFive™ contactless NFC card. A receipt has been sent to your email from Stripe.",
      orderStepsTitle: "What happens next?",
      step1Title: "1. Chip Encoding & Testing",
      step1Desc: "If you ordered a Pre-Programmed card, our technical team encodes your direct 5-star Google review link onto the NTAG215 chip and tests it on iOS & Android.",
      step2Title: "2. Fast Express Dispatch",
      step2Desc: "Your card is securely packed and handed over for registered delivery within 24 to 48 hours.",
      step3Title: "3. Tap & Start Collecting Reviews",
      step3Desc: "Place it on your counter or table. Customers tap their phone and your 5-star Google review window pops up instantly.",
      ctaHome: "Return to Homepage",
      needHelpTitle: "Have any questions about your order?",
      needHelpText: "Reply to your receipt or message us directly on WhatsApp (+351 928 248 322).",
    },
  },
  pt: {
    banner: "🔥 Envio Grátis e Rápido em todas as encomendas esta semana!",
    nav: {
      features: "Vantagens",
      howItWorks: "Como Funciona",
      videoReviews: "Depoimentos",
      calculator: "Simulador",
      pricing: "Produto",
      faq: "Perguntas",
      buyNow: "Pedir Cartão",
    },
    hero: {
      badge: "Avaliado em 4.9/5 por +250 Negócios",
      titleStart: "Consiga 3x Mais Avaliações no Google em",
      titleHighlight: "Segundos com 1 Toque.",
      description: "Acabe com os folhetos de papel e o constrangimento de pedir avaliações. Os clientes apenas aproximam o telemóvel ao cartão e a janela de 5 estrelas do Google abre de imediato.",
      ctaPrimary: "Pedir Cartão de Avaliações — 19,99€",
      ctaSecondary: "Como Funciona",
      bullet1: "Compatível com todos os iPhone e Android",
      bullet2: "Zero mensalidades ou subscrições",
      bullet3: "Envio rápido em 24h a 48h",
      statsTitle: "Impacto médio comprovado:",
      stats1Value: "+240%",
      stats1Label: "Avaliações / Mês",
      stats2Value: "4.8★",
      stats2Label: "Nota Média no Google",
      stats3Value: "3 seg",
      stats3Label: "Para Avaliar",
    },
    cardPreview: {
      title: "Cartão de Avaliações NFC",
      subtitle: "Chip NFC Contactless Integrado",
      tapInstruction: "Aproxime a traseira do telemóvel ao cartão",
      readyBadge: "Chip NFC Passivo • Nunca Precisa de Bateria",
    },
    howItWorks: {
      tag: "Sem Fricção",
      title: "Como Funciona em 3 Passos Fáceis",
      subtitle: "Ideal para balcões de pagamento, mesas de restaurante ou receções.",
      step1Title: "1. Apresente o Cartão",
      step1Desc: "Coloque o cartão mate premium no balcão ou apresente ao cliente logo após o atendimento.",
      step2Title: "2. O Cliente Aproxima o Telemóvel",
      step2Desc: "O cliente aproxima a parte de cima do iPhone ou Android ao cartão. Não precisa de instalar nada.",
      step3Title: "3. Avaliação de 5 Estrelas Deixada",
      step3Desc: "A janela de avaliação do seu negócio abre de imediato no telemóvel com as 5 estrelas selecionadas.",
    },
    calculator: {
      tag: "Faturação e Avaliações",
      title: "Quantas Avaliações Está a Perder Todos os Dias?",
      subtitle: "A maioria dos clientes satisfeitos quer apoiar o seu negócio, mas 95% esquecem-se assim que saem pela porta.",
      sliderLabel: "Clientes satisfeitos estimados por dia:",
      resultTitle: "Novas Avaliações Estimadas:",
      perMonth: "/ mês",
      explanation: "Com apenas 1 cartão no balcão, converter 1 em cada 10 clientes satisfeitos coloca o seu negócio no topo do Google Maps da sua cidade.",
    },
    pricing: {
      tag: "Preços Claros",
      title: "Pagamento Único. Sem Mensalidades Nem Subscrições.",
      subtitle: "Sem custos escondidos. Paga apenas uma vez e utiliza o cartão para sempre.",
      blank: {
        title: "Cartão em Branco",
        tagline: "Configure você mesmo em 2 minutos",
        price: "19,99€",
        originalPrice: "29,99€",
        features: [
          "1x Cartão NFC Premium com acabamento mate",
          "Design oficial de avaliações Google",
          "Compatível com todos os smartphones modernos",
          "Guia passo-a-passo simples incluído",
          "Os seus clientes não precisam de instalar nenhuma aplicação",
          "Envio padrão gratuito",
        ],
        cta: "Comprar Cartão em Branco (19,99€)",
      },
      preProgrammed: {
        badge: "MAIS POPULAR",
        title: "Pré-Programado Pronto a Usar",
        tagline: "Gravamos o perfil do seu negócio antes do envio",
        price: "24,99€",
        originalPrice: "39,99€",
        features: [
          "Tudo o que está incluído no Cartão em Branco",
          "Gravado diretamente com o seu link de avaliação 5 estrelas",
          "Pronto a tirar da caixa e começar a usar",
          "Testado em iOS e Android antes do envio",
          "Envio prioritário em 24 horas",
          "Garantia e suporte direto de funcionamento",
        ],
        cta: "Comprar Pré-Programado (24,99€)",
        inputLabel: "Link do Google Maps ou Nome do Negócio & Cidade:",
        inputPlaceholder: "Ex: Pastelaria Central, Lisboa",
        inputHelp: "Localizamos o seu perfil oficial e gravamos o chip antes do envio.",
        inputError: "Por favor, indique o nome ou link do negócio para configurarmos o cartão.",
      },
      gbpSetup: {
        badge: "SERVIÇO COMPLETO",
        title: "Configuração Completa Google Business",
        tagline: "Criação, verificação e otimização SEO para ficar em #1 na sua cidade",
        price: "199,99€",
        originalPrice: "349,99€",
        freeCardBadge: "🎁 Inclui 1 Cartão Pré-Programado de OFERTA",
        features: [
          "Criação ou auditoria completa do seu Perfil Google Business",
          "Apoio no processo de verificação oficial da Google",
          "Otimização SEO local para aparecer no topo do Google Maps",
          "Configuração de horário, fotos de alta qualidade e catálogo",
          "1x Cartão NFC Pré-Programado de OFERTA incluído (Valor 24,99€)",
          "Consultoria direta para atrair avaliações contínuas",
        ],
        cta: "Contratar Serviço + Cartão Grátis (199,99€)",
        inputLabel: "Nome do Negócio, Cidade e Contacto / WhatsApp:",
        inputPlaceholder: "Ex: Restaurante O Pescador, Cascais (+351 912 345 678)",
        inputHelp: "O nosso especialista entrará em contacto em menos de 24h para iniciar.",
        inputError: "Por favor, indique os dados do negócio e contacto telefónico.",
      },
      guarantee: "Garantia de Satisfação de 30 Dias. Se não ficar 100% satisfeito, devolvemos a totalidade do valor.",
    },
    useCases: {
      tag: "Testado Em Balcões Reais",
      title: "Utilizado em Mais de 250+ Barbearias, Clínicas e Restaurantes",
      items: [
        { icon: "Utensils", title: "Restaurantes e Cafés", desc: "Leve à mesa com a conta para recolher a avaliação no momento alto da refeição.", image: "/media/card-cafe-restaurant.webp" },
        { icon: "Scissors", title: "Barbearias e Salões", desc: "Mostre o corte no espelho e aproxime o telemóvel antes do cliente sair.", image: "/media/card-salon-barber.webp" },
        { icon: "Stethoscope", title: "Clínicas e Consultórios", desc: "No balcão de receção enquanto o paciente faz o pagamento ou marcação.", image: "/media/card-proof-metrics.webp" },
        { icon: "ShoppingBag", title: "Lojas e Estúdios", desc: "Junto ao terminal de pagamento como o toque final de cada compra.", image: "/media/card-podium-studio.webp" },
      ],
    },
    videoReel: {
      tag: "Resultados Reais Comprovados",
      title: "Veja Como os Comerciantes Conseguem 3x Mais Avaliações",
      subtitle: "Assista a casos reais de negócios a recolher avaliações de 5 estrelas diretamente no balcão sem constrangimentos.",
      video1Caption: "“Passei meses a tentar pedir avaliações no Google...”",
      video1Role: "Proprietária de Salão & Estúdio",
      video2Caption: "“Enviávamos mensagens para depois se esquecerem...”",
      video2Role: "Gestora de Clínica de Estética",
      video3Caption: "“O nosso ranking no Google Maps subiu para #1...”",
      video3Role: "Fundador de Barbearia",
      video4Caption: "“Os clientes aproximam o telemóvel a sorrir...”",
      video4Role: "Proprietária de Café Boutique",
      video5Caption: "“Triplicámos o volume mensal em apenas 30 dias...”",
      video5Role: "Diretora de Clínica Dentária",
      video6Caption: "“Sem mensalidades e funciona sempre à primeira.”",
      video6Role: "Gerente de Restaurante",
      soundOn: "Ativar som",
      soundOff: "Silenciar",
    },
    pdp: {
      category: "DISPOSITIVO NFC INTELIGENTE",
      title: "Cartão de Avaliações Google NFC TapFive™",
      rating: "4.9",
      reviewCount: "+250 avaliações",
      inStock: "Em Stock — Expedição em 24h a 48h",
      chooseEdition: "Escolha a Opção:",
      variantBlank: {
        name: "Cartão em Branco",
        desc: "Configure você mesmo em 2 min com app gratuita",
        price: "19,99€",
        originalPrice: "29,99€",
      },
      variantPre: {
        name: "Pré-Programado",
        badge: "MAIS POPULAR",
        desc: "Gravamos o seu perfil Google antes do envio",
        price: "24,99€",
        originalPrice: "39,99€",
      },
      variantGbp: {
        name: "Serviço Google Business + Cartão Grátis",
        badge: "MELHOR VALOR",
        desc: "Otimização SEO completa e verificação do perfil",
        price: "199,99€",
        originalPrice: "349,99€",
      },
      buyNow: "Encomendar Agora",
      featuresTitle: "O que está incluído:",
      features: [
        "1x Cartão PVC Mate Contactless com chip NTAG215",
        "Abertura instantânea de avaliação em iPhone e Android",
        "Zero mensalidades ou subscrições para sempre",
        "Garantia total de satisfação de 30 dias",
      ],
      inputLabelPre: "Link do Google Maps ou Nome do Negócio & Cidade:",
      inputPlaceholderPre: "Ex: Pastelaria Central, Lisboa",
      inputHelpPre: "Nós localizamos e gravamos o link de 5 estrelas no chip antes do envio.",
      inputLabelGbp: "Nome do Negócio, Cidade e Contacto / WhatsApp:",
      inputPlaceholderGbp: "Ex: Restaurante O Pescador, Cascais (+351 912 345 678)",
      inputHelpGbp: "O nosso especialista entrará em contacto em menos de 24 horas.",
    },
    trust: {
      title: "Segurança de Nível Bancário e Tranquilidade",
      ssl: "Encriptação SSL 256-Bit",
      sslDesc: "Os seus dados e pagamento estão totalmente protegidos pelos protocolos seguros da Stripe.",
      shipping: "Envio Rápido e Seguro",
      shippingDesc: "Expedição rápida em correio registado em 24h a 48h.",
      guarantee: "Garantia de 30 Dias",
      guaranteeDesc: "Se não notar resultados ou não ficar 100% satisfeito, devolvemos o seu dinheiro.",
      noSubs: "Zero Mensalidades",
      noSubsDesc: "Pague uma única vez. Sem taxas escondidas, mensalidades ou custos recorrentes.",
    },
    faq: {
      tag: "Tire as Suas Dúvidas",
      title: "Perguntas Frequentes",
      items: [
        {
          q: "O cartão precisa de pilhas ou de ser carregado?",
          a: "Não. O cartão utiliza tecnologia NFC passiva alimentada por indução pelo telemóvel do cliente no momento da aproximação. Dura anos sem manutenção.",
        },
        {
          q: "O cliente precisa de descarregar alguma aplicação?",
          a: "Nunca. Os iPhones e dispositivos Android leem o chip nativamente. Surge de imediato uma notificação no ecrã que abre diretamente o Google.",
        },
        {
          q: "Que telemóveis são compatíveis com o cartão?",
          a: "Praticamente todos os smartphones: todos os iPhones (iPhone XR e posteriores) e mais de 95% dos smartphones Android lançados nos últimos 8+ anos.",
        },
        {
          q: "Como funciona a opção Pré-Programada?",
          a: "Indique o nome do negócio ou link do Google Maps no checkout. Nós encontramos o seu perfil oficial, gravamos o link no chip NFC, testamos e enviamos pronto a usar.",
        },
        {
          q: "Posso alterar o link do cartão mais tarde?",
          a: "Sim. Pode regravar o cartão quando quiser com qualquer aplicação gratuita de NFC (como a 'NFC Tools' na App Store ou Google Play) caso mude de nome ou morada.",
        },
        {
          q: "Existe alguma mensalidade recorrente?",
          a: "Nenhuma. Paga uma única vez pelo cartão e é seu para sempre. Não existem subscrições nem encargos adicionais.",
        },
      ],
    },
    footer: {
      rights: "Todos os direitos reservados. Não afiliado com a Google LLC.",
      secureNotice: "Pagamento 100% Seguro através de encriptação SSL Stripe de 256 bits.",
      terms: "Termos de Serviço",
      privacy: "Política de Privacidade",
      refunds: "Política de Reembolso",
      support: "WhatsApp: +351 928 248 322",
    },
    success: {
      badge: "Pagamento Confirmado",
      title: "Obrigado pela Sua Encomenda!",
      subtitle: "Já estamos a preparar o seu cartão TapFive™ contactless NFC. O recibo oficial foi enviado pela Stripe para o seu e-mail.",
      orderStepsTitle: "O que acontece a seguir?",
      step1Title: "1. Gravação & Verificação do Chip",
      step1Desc: "Se encomendou a versão Pré-Programada, a nossa equipa grava o link direto de 5 estrelas do seu perfil Google no chip NTAG215 e efetua o teste de leitura.",
      step2Title: "2. Expedição Rápida",
      step2Desc: "O seu cartão é embalado com segurança e enviado em correio registado num prazo de 24h a 48h.",
      step3Title: "3. Comece a Receber Avaliações",
      step3Desc: "Basta colocar o cartão no balcão. O cliente aproxima o telemóvel e o Google abre imediatamente no ecrã.",
      ctaHome: "Voltar à Página Principal",
      needHelpTitle: "Alguma dúvida sobre a sua encomenda?",
      needHelpText: "Responda ao e-mail de recibo ou envie mensagem direta no WhatsApp (+351 928 248 322).",
    },
  }
};

